### ISSUE TITLE
Key Error t_span

### ISSUE THREAD

**Issue by TKosir** [ladisk/LadiskDAQ#41]
Since t_span has been moved to add_lines(), add_image() method produces Key error:

An exception occurred in a process:
Traceback (most recent call last):
  File "[c:\LADISK\packages\LadiskDAQ\LadiskDAQ\core.py](file:///C:/LADISK/packages/LadiskDAQ/LadiskDAQ/core.py)", line 182, in wrapper
    return func(*args, **kwargs)
  File "[c:\LADISK\packages\LadiskDAQ\LadiskDAQ\visualization\visualization.py](file:///C:/LADISK/packages/LadiskDAQ/LadiskDAQ/visualization/visualization.py)", line 293, in run
    self.create_ring_buffers()
  File "[c:\LADISK\packages\LadiskDAQ\LadiskDAQ\visualization\visualization.py](file:///C:/LADISK/packages/LadiskDAQ/LadiskDAQ/visualization/visualization.py)", line 397, in create_ring_buffers
    rows = int(max([_['t_span'] * acq.sample_rate for _ in self.plots[source]]))
  File "[c:\LADISK\packages\LadiskDAQ\LadiskDAQ\visualization\visualization.py](file:///C:/LADISK/packages/LadiskDAQ/LadiskDAQ/visualization/visualization.py)", line 397, in <listcomp>
    rows = int(max([_['t_span'] * acq.sample_rate for _ in self.plots[source]]))
KeyError: 't_span'

**Comment by klemengit** [comment]
Fixed.
